-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 10:33:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estrela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estrela` (
  `idestrela` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `massa_kg` DOUBLE NOT NULL,
  `tamanho_km` DOUBLE NOT NULL,
  `luminosidade` DOUBLE NOT NULL,
  `nome_galaxia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestrela`));
  


-- -----------------------------------------------------
-- Table `mydb`.`planeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planeta` (
  `idplaneta` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `massa_kg` DOUBLE NOT NULL,
  `tamanho_km` DOUBLE NOT NULL,
  `habitavel` VARCHAR(2) NOT NULL,
  `estrela_idestrela` INT NOT NULL,
  PRIMARY KEY (`idplaneta`),
   CONSTRAINT `fk_planeta_estrela`
    FOREIGN KEY (`estrela_idestrela`)
    REFERENCES `mydb`.`estrela` (`idestrela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`nave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nave` (
  `idnave` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tripulantes` INT NOT NULL,
  `passageiros` INT NOT NULL,
  PRIMARY KEY (`idnave`));


-- -----------------------------------------------------
-- Table `mydb`.`mapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mapa` (
  `idmapa` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `escala` DOUBLE NOT NULL,
  `orientacao` VARCHAR(45) NOT NULL,
  `quantidade_obstaculos` INT NULL,
  PRIMARY KEY (`idmapa`));

-- -----------------------------------------------------
-- Table `mydb`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viagem` (
  `planeta_idplaneta` INT NOT NULL,
  `nave_idnave` INT NOT NULL,
  `tempo_duracao` VARCHAR(45) NOT NULL,
  `distancia_km` DOUBLE NOT NULL,
  `mapa_idmapa` INT NOT NULL,
  PRIMARY KEY (`planeta_idplaneta`, `nave_idnave`),
   CONSTRAINT `fk_planeta_has_nave_planeta1`
    FOREIGN KEY (`planeta_idplaneta`)
    REFERENCES `mydb`.`planeta` (`idplaneta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planeta_has_nave_nave1`
    FOREIGN KEY (`nave_idnave`)
    REFERENCES `mydb`.`nave` (`idnave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_mapa1`
    FOREIGN KEY (`mapa_idmapa`)
    REFERENCES `mydb`.`mapa` (`idmapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passageiro` (
  `idpassageiro` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `sexo` VARCHAR(2) NOT NULL,
  `profissao` VARCHAR(45) NULL,
  `nave_idnave` INT NOT NULL,
  PRIMARY KEY (`idpassageiro`),
    CONSTRAINT `fk_passageiro_nave1`
    FOREIGN KEY (`nave_idnave`)
    REFERENCES `mydb`.`nave` (`idnave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `mydb`.`tripulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tripulante` (
  `idtripulante` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `sexo` VARCHAR(2) NOT NULL,
  `especializacao` VARCHAR(45) NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `nave_idnave` INT NOT NULL,
  PRIMARY KEY (`idtripulante`),
    CONSTRAINT `fk_tripulante_nave1`
    FOREIGN KEY (`nave_idnave`)
    REFERENCES `mydb`.`nave` (`idnave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);




